In [10]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [11]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [12]:
tokenizer.fit_on_texts(docs)
len(tokenizer.word_index)

17

In [13]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [14]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [15]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.compile('adam','accuracy')

In [19]:
import numpy as np
sequences = np.array(sequences)
sequences = np.clip(sequences, 0, 16)

pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 38ms/step
[[[ 0.01138758  0.04963386]
  [-0.0381778  -0.01842069]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]]

 [[-0.0381778  -0.01842069]
  [-0.0381778  -0.01842069]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]]

 [[ 0.01714971  0.00163149]
  [ 0.01714971  0.00163149]
  [ 0.03513881  0.01389781]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]]

 [[-0.00669507  0.04899183]
  [-0.02462204 -0.03120461]
  [-0.00669507  0.04899183]
  [-0.0381778  -0.01842069]
  [-0.00669507  0.04899183]]

 [[ 0.00733219 -0.00287143]
  [ 0.00795455  0.00135777]
  [ 0.01108355 -0.04824311]
  [-0.01697586  0.00344644]
  [ 0.03287527 -0.03236114]]

 [[-0.03438525 -0.03614914]
  [-0.03438525 -0.03614914]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]
  [ 0.03287527 -0.03236114]]

 [[ 0.01715391 -0.02859565]
  [ 0.01715391 -0.02859565]
  [ 0.03287527 -0.03236114]
  [ 0.032875

In [20]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [22]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [24]:
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense
from keras.preprocessing.sequence import pad_sequences

# Load and pad data
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

# Build model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


782/782 [==============================] - 30s 33ms/step - loss: 0.6111 - acc: 0.6366 - val_loss: 0.4518 - val_acc: 0.7902
Epoch 2/5
782/782 [==============================] - 25s 32ms/step - loss: 0.3894 - acc: 0.8289 - val_loss: 0.4216 - val_acc: 0.8069
Epoch 3/5
782/782 [==============================] - 26s 33ms/step - loss: 0.3259 - acc: 0.8645 - val_loss: 0.4559 - val_acc: 0.8049
Epoch 4/5
782/782 [==============================] - 26s 33ms/step - loss: 0.2863 - acc: 0.8846 - val_loss: 0.4504 - val_acc: 0.8018
Epoch 5/5
782/782 [==============================] - 25s 32ms/step - loss: 0.2637 - acc: 0.8986 - val_loss: 0.5276 - val_acc: 0.7968
